version: "3.8"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    hostname: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database    
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default
  
  backend:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    hostname: backend
    volumes:
        - .:/workspace/
        - ~/.ssh:/home/vscode/.ssh:ro
        - ~/.aws:/home/vscode/.aws:ro 
    tty: true
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - default


volumes:
  db-data:
  

networks:
  default:
    name: postgres-network
