version: "3.8"

services:
  # db:
  #   build:
  #     context: ./db
  #     dockerfile: Dockerfile
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #   volumes:
      
  
  backend:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    volumes:
        - .:/workspace/ 
    tty: true
    command: /bin/sh -c "while sleep 1000; do :; done"